/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 41;
  /** RegularExpression Id. */
  int POSDIGIT = 42;
  /** RegularExpression Id. */
  int ZERO = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int IDENT = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"return\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"=\"",
    "\"switch\"",
    "\"default\"",
    "\":\"",
    "\"case\"",
    "\"for\"",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"boolean\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 39>",
    "<token of kind 40>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
